In [ ]:


!pip install tensorflow
!pip install --upgrade tensorflow
!pip install tensorflow-probability==0.19.0
!pip install keras

import tensorflow as tf
print(tf.__version__)

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 589.8/589.8 MB 2.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.3/5.3 MB 72.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 67.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 76.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 58.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 311.2/311.2 kB 35.5 MB/s eta 0:00:00
  Attempting uninstall: ml-dtypes
    Found existing installation: ml-dtypes 0.2.0
    Uninstalling ml-dtypes-0.2.0:
      Successfully uninstalled ml-dtypes-0.2.0
  Attempting uninstall: h5py
    Found existing installation: h5py 3.9.0
    Uninstalling h5py-3.9.0:
      Successfully uninstalled h5py-3.9.0
  Attempting uninstall: tensorboard
    Found existing installation: tensorboard 2.15.2
    Uninstalling tensorboard-2.15.2:
      Successfully uninstalled tensorboard-2.15.2
  Attempting uninstall: keras
    Fo

In [ ]:


scalar = tf.constant(11)

scalar

<tf.Tensor: shape=(), dtype=int32, numpy=11>

In [ ]:

scalar.ndim

0

In [ ]:

vector = tf.constant([11,15,17,24])

vector

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([11, 15, 17, 24], dtype=int32)>

In [ ]:

vector.ndim

1

In [ ]:


matrix = tf.constant([[17,19,25,23],
                     [15,12,17,17]])

matrix

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[17, 19, 25, 23],
       [15, 12, 17, 17]], dtype=int32)>

In [ ]:

matrix.ndim

2

In [ ]:
changeable = tf.Variable([1,9,15])


changeable

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([ 1,  9, 15], dtype=int32)>

In [ ]:

changeable[1].assign(5)

changeable

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([ 1,  5, 15], dtype=int32)>

In [ ]:

random_1 = tf.random.Generator.from_seed(10)
random_1 = random_1.normal(shape=(4,4))

random_1

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[-0.29604468, -0.21134208,  0.01063002,  1.5165398 ],
       [ 0.2730574 , -0.29925638, -0.3652325 ,  0.61883307],
       [-1.0130817 ,  0.28291714,  1.2132233 ,  0.46988967],
       [ 0.37944326, -0.6664026 ,  0.6054596 ,  0.19181173]],
      dtype=float32)>

In [ ]:

res = tf.constant([[2,5,6],
                  [18,15,12],
                  [9,22,7]])



tf.random.shuffle(res)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[18, 15, 12],
       [ 9, 22,  7],
       [ 2,  5,  6]], dtype=int32)>

In [ ]:

tf.zeros(shape=(2,4))



<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [ ]:


import numpy as np

numarry = np.arange(2,35, dtype=np.int32)

numarry

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34],
      dtype=int32)

In [ ]:

A = tf.constant(numarry, shape=(11,3))


A


<tf.Tensor: shape=(11, 3), dtype=int32, numpy=
array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19],
       [20, 21, 22],
       [23, 24, 25],
       [26, 27, 28],
       [29, 30, 31],
       [32, 33, 34]], dtype=int32)>

In [ ]:



A.shape , A.ndim , tf.size(A) , A.dtype , tf.size(A).numpy()


(TensorShape([11, 3]),
 2,
 <tf.Tensor: shape=(), dtype=int32, numpy=33>,
 tf.int32,
 33)

In [ ]:

A[:2,:2]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [5, 6]], dtype=int32)>

In [ ]:

A[:,:2]

<tf.Tensor: shape=(11, 2), dtype=int32, numpy=
array([[ 2,  3],
       [ 5,  6],
       [ 8,  9],
       [11, 12],
       [14, 15],
       [17, 18],
       [20, 21],
       [23, 24],
       [26, 27],
       [29, 30],
       [32, 33]], dtype=int32)>

In [ ]:

A[:2,:]

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[2, 3, 4],
       [5, 6, 7]], dtype=int32)>

In [ ]:


rank_2_tensor = tf.constant([[10,9],
                             [5,7]])


rank_2_tensor.shape , rank_2_tensor.ndim , tf.size(rank_2_tensor).numpy()

(TensorShape([2, 2]), 2, 4)

In [ ]:


rank_2_tensor[:,-1]


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([9, 7], dtype=int32)>

In [ ]:

tf.expand_dims(rank_2_tensor, axis=0)



<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  9],
        [ 5,  7]]], dtype=int32)>

In [ ]:
tf.expand_dims(rank_2_tensor, axis=-1)


<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 9]],

       [[ 5],
        [ 7]]], dtype=int32)>

In [ ]:


tf.expand_dims(rank_2_tensor, axis=1)

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  9]],

       [[ 5,  7]]], dtype=int32)>

In [ ]:


rank_3_tensor = rank_2_tensor[..., tf.newaxis]

rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 9]],

       [[ 5],
        [ 7]]], dtype=int32)>

In [ ]:

tensor = tf.constant([[2,5],
                      [8,10]])


tensor - 1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 4],
       [7, 9]], dtype=int32)>

In [ ]:


tf.multiply(tensor,20)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 40, 100],
       [160, 200]], dtype=int32)>

In [ ]:

tensor1 = tf.constant([[1,2,5],
                       [7,2,1],
                       [3,3,3]])


tensor2 = tf.constant([[3,5],
                       [6,7],
                       [1,8]])

tf.matmul(tensor1,tensor2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [ ]:

tensor1 @ tensor2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [ ]:

tf.transpose(tensor1)



<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 7, 3],
       [2, 2, 3],
       [5, 1, 3]], dtype=int32)>

In [ ]:

tf.reshape(tensor2, shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[3, 5, 6],
       [7, 1, 8]], dtype=int32)>

In [ ]:

tf.tensordot(tensor1,tensor2,axes=1)



<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [ ]:

A = tf.constant([5,16])

A,A.dtype

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 5, 16], dtype=int32)>,
 tf.int32)

In [ ]:


B = tf.cast(A, dtype=tf.float16)

B,B.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 5., 16.], dtype=float16)>,
 tf.float16)

In [ ]:


C = tf.constant(np.random.randint(0,100,size=50))

C

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([39, 25, 19, 30, 40, 28, 67, 57,  2, 28,  8, 35, 67, 44,  0, 80,  4,
       93, 65, 12, 58, 76, 45, 69, 87, 83, 97, 61, 11, 84, 91, 95, 19, 50,
       71, 57,  6, 39, 31,  2, 94, 94, 90, 51,  6, 12, 74, 95, 62, 93])>

In [ ]:


tf.reduce_min(C)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [ ]:
tf.reduce_mean(C)



<tf.Tensor: shape=(), dtype=int64, numpy=50>

In [ ]:

tf.reduce_sum(C)


<tf.Tensor: shape=(), dtype=int64, numpy=2546>

In [ ]:

D = tf.constant([-7,-10])

tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [ ]:

import tensorflow_probability as tfp

tfp.stats.stddev(tf.cast(C , dtype=tf.float32))

ValueError: Arg specs do not match: original=FullArgSpec(args=['input', 'dtype', 'name', 'layout'], varargs=None, varkw=None, defaults=(None, None, None), kwonlyargs=[], kwonlydefaults=None, annotations={}), new=FullArgSpec(args=['input', 'dtype', 'name'], varargs=None, varkw=None, defaults=(None, None), kwonlyargs=[], kwonlydefaults=None, annotations={}), fn=<function ones_like_v2 at 0x7b5bd5dc77f0>

In [ ]:

tf.math.reduce_std(tf.cast(C , dtype=tf.float32))



<tf.Tensor: shape=(), dtype=float32, numpy=31.317623>

In [ ]:

tf.math.reduce_variance(tf.cast(C , dtype=tf.float32))

In [ ]:

tf.random.set_seed(42)

F = tf.random.uniform(shape=[50])

F



<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:


tf.argmax(F)


<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:


tf.reduce_max(F)

In [ ]:

F[tf.argmax(F)] == tf.reduce_max(F)


<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [ ]:



tf.random.set_seed(42)

G = tf.random.uniform(shape=[1, 1, 1, 1,50])

G



<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:


G_squeezed = tf.squeeze(G)

G_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:


l1 = [ 0,1,2,3]

In [ ]:


tf.one_hot(l1,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:

tf.one_hot(l1,depth=4,on_value = 'I am the Champ', off_value = 'I am an undefeated mma fighter')


<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'I am the Champ', b'I am an undefeated mma fighter',
        b'I am an undefeated mma fighter',
        b'I am an undefeated mma fighter'],
       [b'I am an undefeated mma fighter', b'I am the Champ',
        b'I am an undefeated mma fighter',
        b'I am an undefeated mma fighter'],
       [b'I am an undefeated mma fighter',
        b'I am an undefeated mma fighter', b'I am the Champ',
        b'I am an undefeated mma fighter'],
       [b'I am an undefeated mma fighter',
        b'I am an undefeated mma fighter',
        b'I am an undefeated mma fighter', b'I am the Champ']],
      dtype=object)>

In [ ]:

H = tf.range(1,10)

H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:


tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:


tf.sqrt(tf.cast(H, dtype=tf.float16))

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([1.   , 1.414, 1.732, 2.   , 2.236, 2.45 , 2.646, 2.828, 3.   ],
      dtype=float16)>

In [ ]:

tf.math.log(tf.cast(H, dtype=tf.float16))

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([0.    , 0.6934, 1.099 , 1.387 , 1.609 , 1.792 , 1.946 , 2.08  ,
       2.197 ], dtype=float16)>

In [ ]:


J = tf.constant(np.array([3., 7., 10.]))

J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [ ]:


np.array(J)

array([ 3.,  7., 10.])

In [ ]:

tf.config.list_physical_devices('GPU')


[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:

!nvidia-smi


Wed May 15 08:40:58 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   59C    P0              28W /  70W |    107MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--